# Generated by Django 3.0.4 on 2020-03-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='depart_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
